import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:tts_bandmate/features/auth/data/models/band_summary.dart';
import 'package:tts_bandmate/features/bookings/data/bookings_repository.dart';
import 'package:tts_bandmate/features/bookings/data/models/booking_detail.dart';
import 'package:tts_bandmate/features/bookings/providers/bookings_provider.dart';
import 'package:tts_bandmate/features/bookings/screens/booking_contract_screen.dart';
import 'package:tts_bandmate/shared/cache/cache_invalidator.dart';

// The "Change to a contract type" action on the verbal-agreement view was a
// "(coming soon)" stub. It now PATCHes contract_option with the same
// vocabulary as the create form.

class _FakeRepo extends BookingsRepository {
  _FakeRepo() : super(Dio());

  int updateCalls = 0;
  String? capturedContractOption;

  @override
  Future<BookingDetail> updateBooking(
    int bandId,
    int bookingId, {
    String? name,
    int? eventTypeId,
    String? price,
    String? status,
    String? contractOption,
    String? notes,
    String? depositType,
    String? depositValue,
  }) async {
    updateCalls++;
    capturedContractOption = contractOption;
    return _detail(contractOption: contractOption ?? 'none');
  }
}

class _NoopInvalidator extends CacheInvalidator {
  _NoopInvalidator(super.ref);

  @override
  void onBookingDetailChanged(
      {required int bandId,
      required int bookingId,
      String? contractEnvelopeId}) {}
}

BookingDetail _detail({String contractOption = 'none'}) => BookingDetail(
      id: 1,
      name: 'Test Booking',
      startDate: '2026-06-01',
      endDate: '2026-06-01',
      eventCount: 1,
      isMultiEvent: false,
      isPaid: false,
      contacts: const [],
      events: const [],
      contractOption: contractOption,
      status: 'confirmed',
      band: const BandSummary(id: 1, name: 'Band', isOwner: true),
    );

Future<_FakeRepo> _pumpNoneScreen(WidgetTester tester) async {
  final repo = _FakeRepo();
  await tester.pumpWidget(
    ProviderScope(
      overrides: [
        bookingDetailProvider.overrideWith((ref, args) async => _detail()),
        bookingsRepositoryProvider.overrideWithValue(repo),
        cacheInvalidatorProvider.overrideWith(_NoopInvalidator.new),
      ],
      child: const CupertinoApp(
        home: BookingContractScreen(bandId: 1, bookingId: 1),
      ),
    ),
  );
  await tester.pump();
  return repo;
}

void main() {
  testWidgets('picker offers the create-form vocabulary, no coming-soon',
      (tester) async {
    await _pumpNoneScreen(tester);

    await tester.tap(find.text('Change to a contract type'));
    await tester.pumpAndSettle();

    expect(find.text('Generated by Bandmate'), findsOneWidget);
    expect(find.text('Upload my own'), findsOneWidget);
    expect(find.text('No contract'), findsOneWidget);
    expect(find.textContaining('coming soon'), findsNothing);
  });

  testWidgets('choosing Generated by Bandmate PATCHes contract_option',
      (tester) async {
    final repo = await _pumpNoneScreen(tester);

    await tester.tap(find.text('Change to a contract type'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Generated by Bandmate'));
    await tester.pumpAndSettle();

    expect(repo.updateCalls, 1);
    expect(repo.capturedContractOption, 'default');
  });

  testWidgets('cancel and re-picking the current option make no call',
      (tester) async {
    final repo = await _pumpNoneScreen(tester);

    await tester.tap(find.text('Change to a contract type'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Cancel'));
    await tester.pumpAndSettle();

    await tester.tap(find.text('Change to a contract type'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('No contract'));
    await tester.pumpAndSettle();

    expect(repo.updateCalls, 0);
  });
}
